### ISSUE TITLE
YOu gram sukkk

### ISSUE THREAD

**Issue by mortal1** [Balajanovski/3D-Tetris#1]
down arrow should speed up the block's descent
The blocks of the same shape orientation should be the same colour - this helps the colour association

**Comment by Balajanovski** [comment]
Suggestions implemented in commit [db865c0a40d61568220c498abfa3ef8a4f80d4aa](https://github.com/Balajanovski/3D-Tetris/commit/db865c0a40d61568220c498abfa3ef8a4f80d4aa)
